name: Unity Tests
on:
  push:
    branches: # Only run jobs if files changed on this branch
      - master
    paths: # Only run jobs if files changed at these paths
      - '.github/workflows/**'
      - 'Assets/**'
      - 'Packages/**'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  # Run the Unity tests
  tests:
    name: Run Unity 2021.3 tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          lfs: true

      # Cache library folder for faster tests
      - name: Cache library
        uses: actions/cache@v3.0.11
        with:
          path: Library
          key: LibraryFolder
          restore-keys: |
            LibraryFolder

      # Run play mode tests
      - name: Play mode tests
        uses: game-ci/unity-test-runner@v2
        id: playmode_tests
        with:
          testMode: playmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: playmode-artifacts
          checkName: Play mode test results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+AuroraPunks.ScriptableValues'

      # Run edit mode tests
      - name: Edit mode tests
        uses: game-ci/unity-test-runner@v2
        id: editmode_tests
        with:
          testMode: editmode
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactsPath: editmode-artifacts
          checkName: Edit mode test results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+AuroraPunks.ScriptableValues'

      # Upload test results
      - name: Upload play mode results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results for play mode
          path: ${{ steps.playmode_tests.outputs.coveragePath }}

      # Upload test coverage results
      - name: Upload edit mode results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results for edit mode
          path: ${{ steps.playmode_tests.outputs.coveragePath }}

      - name: Check directory
        run: |
          ls
